### ISSUE TITLE
Pull Full Microsoft User Profile including Security Groups

### ISSUE THREAD

**Issue by stevegroner** [wpo365/wpo365-login#19]
Would be great if we could pull the full user profile data from Microsoft including security groups and then in the WP settings be able to enter names of security groups the user needs to be part of in order to authenticate.  This way we could be more granular with who has access to the sites based on AzureAD security group membership.  This would mean that you would need to somehow destroy the token or invalidate the token if the user does NOT meet the security group membership requirements so future calls to the site would prompt again for Microsoft credentials.

**Comment by brandontravis** [comment]
second

**Comment by wpo365** [comment]
@stevegroner and @brandontravis please have a look at the new premium version of the plugin https://www.wpo365.com/downloads/wordpress-office-365-login-premium/ and for a brief introduction on how to configure it you can read the updated installation guide https://www.wpo365.com/how-to-install-wordpress-office-365-login-plugin/#accesscontrol

**Comment by brandontravis** [comment]
Looks pretty amazing. I've hacked your original plugin to pieces and
accomplished what I needed but I'm sure your premium plugin does a better
job. Thanks!
