### ISSUE TITLE
'login tampered with' redirect when clicking on a link from powerpoint (i know, i know...)

### ISSUE THREAD

**Issue by sebastiangug** [wpo365/wpo365-login#21]
So this is a weird one. I've been through some errors in the past when trying to access the HTTP version of things would result in a redirect to wp-login page and getting a 'tampered with' message and all that.

Fixed it by forcing seo-safe redirect to HTTPS of HTTP and now all is good and bright.

But this is a proper weird one here.

I've tested it extensively in every environment I can think of and apparently when you get to the website by clicking on links within a word document or a powerpoint presentation, the same thing happens.

Will continue trying to fix this but help is really appreciated!

Thanks!

**Comment by sebastiangug** [comment]
Googled a few issues with links within office products and how they handle things. turned out all I had to do is add this in the apache/nginx settings:

RewriteEngine on
RewriteCond %{HTTP_USER_AGENT} ms-office [NC]
RewriteRule ^.* - [R=200,L]

Thanks anyway!

**Comment by wpo365** [comment]
The issue with Word and Office Applications in general is that they handle the connection internally. This means that the Office application creates a "private" connection separate from the existing one and this connection is without the necessary authentication tokens and cookies at first.

**Comment by sebastiangug** [comment]
I see, thanks! Really great plug-in by the way!

**Comment by wpo365** [comment]
Thanks! You are more than welcome to leave a review :) https://wordpress.org/plugins/wpo365-login/#reviews

**Comment by sebastiangug** [comment]
Already have! :)
