### ISSUE TITLE
Setup Error?

### ISSUE THREAD

**Issue by eyersee** [wpo365/wpo365-login#23]
After setting up the authentication tool I am getting routed to the below URL
Can I ask for some help with this please, I have looked through all the manuals and alike for help
Domain Name:  http://mslit.net 

URL: 
https://login.microsoftonline.com/https://sso.ms.org.au/oauth2/authorize?client_id=91605fd0-de30-4e49-ad32-xxxxxxxxxxxx&response_type=id_token+code&redirect_uri=http%3A%2F%2Fmslit.net%2Fap&response_mode=form_post&scope=openid&resource=91605fd0-de30-4e49-ad32-xxxxxxxxxxxx&state=http%3A%2F%2Fmslit.net%2Fwp%2F&nonce=H9tCIYHVsN3lU2QuNAitSh%2FDFNJOj9DnNqIj1G6YHj57Im5vbmNlIjoiV1U5VlVsOU9UMDVEUlY5VFJVTlNxxxxx

**Comment by eyersee** [comment]
I should note after setting up the tool I think that now I am read only in the admin account, thus I am not sure how I will be able to edit the settings now?

**Comment by wpo365** [comment]
Hi  @eyersee 

Firstly, I've updated your initial issue to obscure some of your private details e.g. client id etc.

Secondly, it is expected that you are redirected to Microsoft. This is basically what the plugin does: Redirect you to Microsoft so you can authenticate with your corporate account. When you are already logged on, you will be automatically be redirected back to your WordPress site ... And when you are being redirected back, the plugin receives some basic profile information (name, email address etc.) and will compare this information with existing users in WordPress ... If no user with the email address returned by Microsoft exists in WordPress, the plugin will create a new user (you can disable this functionality - in which case the user won't be granted access instead). 

Now, in your case it seems that all works OK. However, it seems that when you are redirected from Microsoft, a new user has been created with the email address matching your Office 365 email address and this user will have a default role according to the settings (by default "Subscriber" also this can be changed). So probably you would need to log off (as the Office 365 user). This will load the default login page (wp-login.php) and then log on (manually) with the account that you specified when you installed WordPress ...

**Comment by eyersee** [comment]
Thank you for your help.
Progressed to now getting this error 
Message:  AADSTS90014: The request body must contain the following parameter: 'client_id'.

**Comment by wpo365** [comment]
Hi @eyersee Have you seen the online documentation on our website https://www.wpo365.com/wpo365-login-documentation/ If you follow this, you should be up and running in 5 to 10 minutes ...
