### ISSUE TITLE
Logins fail and redirected to wp-login.php with 'Tampered with' message

### ISSUE THREAD

**Issue by suffolklibraries** [wpo365/wpo365-login#24]
Hi there,

Most of our logins have started to fail. What was an intermittent problem has become more common over the last couple of days, to the extent that most logins fail.

Visitors are redirected to O365 for login. When they enter their credentials the login fails and users are redirected to wp-login.php They also get a message saying their login may have been tampered with.

The Azure AD reply and home URIs match those in the plugin settings. We're using SSL and have checked the 'Skip SSL host verification' box.

I've emailed a debug file.

Thanks,

Leon

**Comment by TomBayne** [comment]
Was this fixed? I am having the same issue on HTTP (no SSL). Do I need SSL?
