### ISSUE TITLE
First time user login issue

### ISSUE THREAD

**Issue by bryanwillis** [wpo365/wpo365-login#33]
This is similar to my [previously posted Issue](https://github.com/wpo365/wpo365-login/issues/32), but I wasn't sure if it was caused by the same thing so I figured I'd post it separately.

**Here's the scenario:** A newly added O365 employee/user was just sent their username and password and info about the intranet. Instead of going to try and login on Microsoft's site first they go directly to the Intranet protected wordpress site and try to login there. They get logged in and are asked to verify authentication. Once they do this instead of getting directed to the appropriate home page, they get redirected to the wp-login.php page, if the page is is public through the blacklist settings. 

https://mbi.team/wp-login.php?reauth=1&login_errors=TAMPERED_WITH

However, the user actually is logged in already. If the user then types in the homepage in the URL they get directed successfully there without any issues or being asked to login again.

**Comment by bryanwillis** [comment]
I thought maybe extending the "Leeway time" would fix this because maybe it was just taking too long to login, but that didn't help

**Comment by wpo365** [comment]
Hi @bryanwillis The interesting part here is the TAMPERED_WITH error code. It seems that along the lines the user's context becomes invalid or that the ID token cannot be decoded successfully. Is it possible to reproduce this error and if so, could you send me the log file (directly via email)? I'm happy to investigate and find out which of the errors causes the invalidation of the login attempt.

**Comment by wpo365** [comment]
Hi @bryanwillis Were you able to resolve the issue and can I close the issue?

**Comment by wpo365** [comment]
No replies received so I'm closing this issue.
