### ISSUE TITLE
Error message when new user try to login

### ISSUE THREAD

**Issue by Dihme** [wpo365/wpo365-login#35]
Hello,

I have the premium version of the plugin and i have a problem when new users try to login. The user is redirected to the wp-login page with the error "CHECK_LOG". I don't know where to find these logs. There is nothing in the PHP logs. Can you help me? Thank you.

![capture](https://user-images.githubusercontent.com/44196415/47011044-1e865680-d141-11e8-8e6c-acffd1b0a164.PNG)

**Comment by wpo365** [comment]
Hi @Dihme 

Firstly, please feel free to connect directly with me per email. You can use the [email form on the website to get in touch](https://www.wpo365.com/contact/).

Secondly, to enable debug logging you can follow the instruction in the [online documentation (first paragraph)](https://www.wpo365.com/troubleshooting-the-wpo365-login-plugin/). I will happily help you analyze the log file, once you have it ...

And last but not least: I had another case this very morning and I could see in the log file that Azure AD was configured in such way that the user needed to be explicitely assigned to the application registration (error message in the log was **AADSTS50105: The signed in user is not assigned to a role for the application**) To check this you can navigate to [https://portal.azure.com](https://portal.azure.com), then select **Azure Active Directory** and click **Enterprise Applications**. Now find the **Application Registration** and finally click **Properties** ... 

![image](https://user-images.githubusercontent.com/32041702/47012931-d584d100-d145-11e8-860d-d6c503ad6e1b.png)

**Comment by Dihme** [comment]
Thank you for the quick reply,

Il finally found out what was the problem. I had added the user to the security group, but not to the allowed users in the entreprise application. It’s OK now.

Best Regards,

[cid:image001.jpg@01D46561.FDA614A0]

Mehdi Mamou
OL ORGANISATION
Développeur Web

Groupama Stadium
10 avenue Simone Veil
CS 70712
69153 Décines Cedex

mmamou@ol.fr
Bureau +33 4 81 07 47 03





De : WPO365 <notifications@github.com>
Envoyé : mardi 16 octobre 2018 13:18
À : wpo365/wpo365-login <wpo365-login@noreply.github.com>
Cc : Mehdi Mamou <mmamou@ol.fr>; Mention <mention@noreply.github.com>
Objet : Re: [wpo365/wpo365-login] Error message when new user try to login (#35)


Hi @Dihme<https://github.com/Dihme>

Firstly, please feel free to connect directly with me per email. You can use the email form on the website to get in touch<https://www.wpo365.com/contact/>.

Secondly, to enable debug logging you can follow the instruction in the online documentation (first paragraph)<https://www.wpo365.com/troubleshooting-the-wpo365-login-plugin/>. I will happily help you analyze the log file, once you have it ...

And last but not least: I had another case this very morning and I could see in the log file that Azure AD was configured in such way that the user needed to be explicitely assigned to the application registration (error message in the log was AADSTS50105: The signed in user is not assigned to a role for the application) To check this you can navigate to https://portal.azure.com, then select Azure Active Directory and click Enterprise Applications. Now find the Application Registration and finally click Properties ...

[image]<https://user-images.githubusercontent.com/32041702/47012931-d584d100-d145-11e8-860d-d6c503ad6e1b.png>
