### ISSUE TITLE
Premium update fail

### ISSUE THREAD

**Issue by Dihme** [wpo365/wpo365-login#39]
Hello,

I have the 4.6 version of the plugin and i want to update it but it fails. The error message is : 
cURL error 6: Could not resolve host: no-download-link-found

Can you help me ? Thanks.

**Comment by wpo365** [comment]
Hi @Dihme This can happen when you didn't enter your personal download link on the first tab of the WPO365 Options page. Please contact us via the contact form on the website http://www.wpo365.com/contact/ in case you've lost your download link that was sent to you in the intial Download Notification email.

Best wishes
Thanks, Marco

**Comment by Dihme** [comment]
Thank you ! So i added the link like that :

define( 'WPO_LOGIN_DOWNLOAD_LINK', 'https://www.wpo365.com/index.php?eddfile=2078%3A442%3A1%3A1&ttl=1570889327&file=1&token=021013ccb67b3bc18b630ddae27bf9e4' );

But it doesn’t work even now.
Please find my configuration in the associated file.

Best Regards,

[cid:image002.jpg@01D493C6.3720EF60]

Mehdi Mamou
OL ORGANISATION
Développeur Web

Groupama Stadium
10 avenue Simone Veil
CS 70712
69153 Décines Cedex

mmamou@ol.fr
Bureau +33 4 81 07 47 03





De : WPO365 <notifications@github.com>
Envoyé : vendredi 14 décembre 2018 12:54
À : wpo365/wpo365-login <wpo365-login@noreply.github.com>
Cc : Mehdi Mamou <mmamou@ol.fr>; Mention <mention@noreply.github.com>
Objet : Re: [wpo365/wpo365-login] Premium update fail (#39)


Hi @Dihme<https://github.com/Dihme> This can happen when you didn't enter your personal download link on the first tab of the WPO365 Options page. Please contact us via the contact form on the website http://www.wpo365.com/contact/ in case you've lost your download link that was sent to you in the intial Download Notification email.

Best wishes
Thanks, Marco

**Comment by wpo365** [comment]
Sorry ... You cannot post your download link on a public website nor should you post your private details. Please contact us via the contact form.
