### ISSUE TITLE
365 Avatar images not showing on backend

### ISSUE THREAD

**Issue by Nadeemxb** [wpo365/wpo365-login#41]
Since the last update to the plugin our user images are not all showing on the wordpress backend.  About 90% of them are missing.  They all still show on the front end of the site - even in the admin bar.  Has anyone else had this issue?

**Comment by wpo365** [comment]
Hi @Nadeemxb It's the first time I heard about this but I'll investigate it and will report back here.

**Comment by Nadeemxb** [comment]
Hi
Please hold off for now.  It looks like having a high interval for the Avatar refresh/sync was causing them to drop off.  I've reduced it to 1hr (as a test) and images are starting to re-appear.  Odd that they were fine on the front end still though.

**Comment by Nadeemxb** [comment]
Same problem again.  However a different cause.  If we enable multi-factor authentication for accounts in 365 then those accounts do not sync gravatar images.  Is this a known issue or is there a setting we need to change within the plugin for multi-factor enabled accounts?

**Comment by wpo365** [comment]
Hi @Nadeemxb I think MFA is indeed preventing the plugin to get an access token from Azure AD. You should look for ways to exclude the Application Registration from MFA e.g. using conditional access https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/app-based-mfa.
