### ISSUE TITLE
Cannot login when using HTTP

### ISSUE THREAD

**Issue by TomBayne** [wpo365/wpo365-login#42]
Hi, I recieve an error 'Your login has been tampered with" when trying to log in. I am using HTTP, with no SSL. Is this the problem?

**Comment by chrisstayton** [comment]
From my experience, you will have to go to portal.office.com and completely log out. Then go to the website where the WPO365 Login Plugin is installed and try again. Its an issue with Microsoft, not the plugin. Also, be sure to add the user to WordPress.

**Comment by wpo365** [comment]
Hi @tb0111  There can be multiple reasons for this error to occur. If possible, please activate WordPress debug logging as described in the [first paragraph on the website](https://www.wpo365.com/troubleshooting-the-wpo365-login-plugin/) and send me the log file (info at wpo365.com) ... I'm happy to have a look. A possible reason can be caching (see the [online documentation](https://www.wpo365.com/dont-try-bypass-cache/) for more background on this). Other, less likely reasons can be that your server's system time is skewed (and hence the plugin is lead to believe that the token should not be used anymore) or that the plugin isn't able to decypher the encrypted information from Microsoft.

**Comment by TomBayne** [comment]
> 
> 
> From my experience, you will have to go to portal.office.com and completely log out. Then go to the website where the WPO365 Login Plugin is installed and try again. Its an issue with Microsoft, not the plugin. Also, be sure to add the user to WordPress.

This worked
