### ISSUE TITLE
after last update 5 days ago, it errors saying it can't find user

### ISSUE THREAD

**Issue by bluenevus** [wpo365/wpo365-login#44]
after last update 5 days ago, it errors saying it can't find user then goes to a 404 error

**Comment by wpo365** [comment]
Microsoft recently moved from App registration V1 to V2 and with that a number of “defaults” changed and I followed with the plugin. Basically, the ID token received from Microsoft contains less “default” claims and some tokens that the plugin used to “fill in” you should either now request explicitly or you should check the box Use older ID token parser on the Miscellaneous tab. To request the now optional claims is documented online here https://www.wpo365.com/azure-application-registration/#upn.

**Comment by bluenevus** [comment]
thanks.  works great
