### ISSUE TITLE
Not finding existing user

### ISSUE THREAD

**Issue by alexkillby** [wpo365/wpo365-login#49]
Excuse me if this is a problem of my own making, but all of the sudden I have a certain selection of users from the O365 tenant the app is registered with (it allows external users as well) and none of the users can authenticate. After troubleshooting it seems that during the login process despite having existing Wordpress users matching all Azure identity UPN's that are trying to authenticate, but the plugin does not identify those users, and tries to create a new one instead. I have deliberately turned off creation of accounts so that fails, and I have tried deleting all and recreating all Wordpress user accounts, but the plugin will still not match their login on the basis of UPN->email address, and still tries to create a new account. On the latest version at the moment.

**Comment by wpo365** [comment]
@alexkillby Please open a new support request (see [https://www.wpo365.com/contact/](https://www.wpo365.com/contact/)).
