### ISSUE TITLE
some Users cannt login

### ISSUE THREAD

**Issue by R3alflash** [wpo365/wpo365-login#51]
Hey,

since some days some users cannt login with sso. There is the error message "Your ID token could not be processed. Please contact your System Administrator."

Azure AD said no error

WP Plugin Log said: 

07-09-2021 08:25:26.309593
ERROR
Wpo\Services\Authentication_Service::authenticate_oidc_user -> ID token could not be extracted from request storage.

Do you have any help?

PS: We have an licensed Plugin :)

**Comment by wpo365** [comment]
Hi

Can you please re-send your request via http://www.wpo365.com/contact/? This will add your request to the support queue and hence is tracked!

Thanks you for your patience!

- Marco

**Comment by R3alflash** [comment]
sure :)
